[FIELDLINES] allow start from plasma boundary given in VMEC `INDATA`, not only `wout`
PrincetonUniversity/STELLOPT pull request #241
Opened 2024-06-03 15:32 UTC by jonathanschilling

These changes allow to provide the command-line argument `-edge` to FIELDLINES not only in combination with tracing over a VMEC equilibrium, but also in vacuum (`-vac`).
The plasma boundary geometry is then read from the VMEC `INDATA` namelist using `RBC` and `ZBS` (and in case of `lasym`, also `RBS` and `ZBC`). Furthermore, `nfp`, `mpol` and `ntor` are needed.

Additional input parameters (in the `FIELDLINES_INPUT` namelist) named `nstart_pol` and `nstart_tor` are provided to specify how many grid points over the plasma boundary are to be used in each of the tangential directions. They default to 0, in which case (as if they are not specified in the `FIELDLINES_INPUT` namelist) operation defaults to `int(floor(sqrt(maxlines)))` per direction, as previously implemented.

2024-06-04 09:30 UTC, jonathanschilling commented
Note: Assuming one has an existing `wout` file, but only wants to use the plasma boundary geometry from there, one can copy that plasma boundary geometry into a new VMEC `indata` namelist using the `wout2indata` tool from #245.

2024-06-04 15:04 UTC, jons-pf commented
@lazersos FYI, I think this should now be compatible again with the recently merged py_stel update.

2024-06-12 08:46 UTC, lazersos commented on LIBSTELL/Sources/Modules/fieldlines_input_mod.f90
> +      WRITE(iunit_out,outint) 'NSTART_POL',nstart_pol
These should only be written out if they're >0.

2024-06-12 08:48 UTC, lazersos requested changes
The modifications in FIELDLINES_INIT_MGRID and COIL (All the BCASTS) shouldn't be there.  When you call init_edgestart, you should re-read the `INDATA` namelist.  This better compartmentalizes the code.  Also `mylocalmaster` doesn't need to be broadcast.

2026-02-02 15:25 UTC, closed without merging