Feature/beams3 d toroidal rotation
PrincetonUniversity/STELLOPT pull request #317
Opened 2024-12-02 15:38 UTC by kudav

This adds the toroidal rotation to the collisional calculation to BEAMS3D, both for deposition and slowing down. 
New input namelist parameters are OMEG_AUX_S and OMEG_AUX_F, giving the radial profile of the angular rotation velocity. 
The toroidal velocity changes the relative velocity (i.e. the parallel velocity) in the collision calculation, which takes place in the particle frame.
Note that the sign of the rotation is positive in the direction of the magnetic field, not in the geometric toroidal angle!

The orbit effects of toroidal rotation can be incorporated by including the equivalent radial electric field.

2024-12-03 08:21 UTC, lazersos requested changes
Major changes necessary.

2024-12-03 08:21 UTC, lazersos commented on BEAMS3D/Sources/beams3d_init_continuegrid.f90
> +      TE = 0; NE = 0; TI=0; S_ARR=1.5; U_ARR=0; POT_ARR=0; ZEFF_ARR = 1;OMEG_ARR = 1;
Shouldn't `OMEG_ARR=0` here?

2024-12-03 08:21 UTC, lazersos commented on BEAMS3D/Sources/beams3d_init_eqdsk.f90
> +         TE = 0; NE = 0; TI=0; S_ARR=1.5; U_ARR=0; POT_ARR=0; ZEFF_ARR = 1;OMEG_ARR = 1;
Shouldn't `OMEG_ARR=0` here.

2024-12-03 08:21 UTC, lazersos commented on BEAMS3D/Sources/beams3d_init_fieldlines.f90
> +         TE = 0; NE = 0; TI=0; S_ARR=1.5; U_ARR=0; POT_ARR=0; ZEFF_ARR = 1;OMEG_ARR = 1;
Shouldn't `OMEG_ARR=0` here?

2024-12-03 08:21 UTC, lazersos commented on BEAMS3D/Sources/beams3d_physics_mod.f90
This needs to be redone. In the end all you want to do is:
`vll_temp = vll_temp - omeg_temp*r_temp`
The way this was implmented needs to be drastically chagned.
- Remove the call to `beams3d_MODB` this is handled below in the statement block.
- Remove `beams3d_lab_to_plasma` and `beams3d_plasma_to_lab`
- Add the spline evaluation to the big block of spline evaluations.
- Add the modification to vll to the top of the helpers block `vll = vll + omeg_temp*r_temp`
- At the end of the `beams3d_physics_gc` subroutine add the velocity modification back in. `q(4) = q(4) - omega_temp*r_temp`.

2024-12-03 08:21 UTC, lazersos commented on BEAMS3D/Sources/beams3d_write.f90
> +                  CALL write_var_hdf5(fid,'OMEG_ARR',nr,nphi,nz,ier,DBLVAR=OMEG_ARR,ATT='Toroidal rotation [m/s]',ATT_NAME='description')
`ATT` is wrong it is in units of `rad/s`.

2024-12-03 08:21 UTC, lazersos commented on BEAMS3D/Sources/beams3d_write_ascoth4.f90
Doesn't look like you actually output omega_I based on your modifications.

2024-12-03 08:21 UTC, lazersos commented on LIBSTELL/Sources/Modules/beams3d_input_mod.f90
> +      OMEG_AUX_F = -1
`OMEG_AUX_F = 0`

2024-12-03 08:21 UTC, lazersos commented on LIBSTELL/Sources/Modules/beams3d_input_mod.f90
You should also make sure this new variable is written out in the namelist write routine.

2024-12-03 14:39 UTC, lazersos requested changes
There is still a slight issue with how the velocity is handled.

2024-12-03 14:39 UTC, lazersos commented on BEAMS3D/Sources/beams3d_physics_mod.f90
OK, I'm being a bit fussy here but the use of `omeg_temp` is inconsistent betweeen `beams3d_physics_gc` and `beams3d_physics_fo`. In `beams3d_physics_gc` the variable is treated as the parallel velocity while in `beams3d_physics_fo` it modifies `vll` but looks like `v_toroidal`. 

I think it's safe to assume that `omeg_temp` should be treated as the toroidal rotation. So the 329 in `beams3d_physics_gc` should read
```fortran
vll = vll - omeg_temp*r_temp*bphi_temp/modb
```
And later on as well.  This requires the quantity `BPHI4D` be splined as well.
In `beams3d_physics_fo` the modification should not be made to `vll` but rather `q(5)` as this is toroidal velocity.

2024-12-04 13:33 UTC, lazersos commented
I've made a bunch of changes so that the rotational velocity is handled better. Additionally, the multi-pass deposition option breaks the benchmark becasue there is no explicit wall.

2024-12-04 13:48 UTC, lazersos commented
Multi-pass is now enabled but only for non-plasma_only runs.

2024-12-05 11:00 UTC, lazersos approved these changes
From my point of this branch is now ready to merge.

2024-12-05 11:10 UTC, merged

2024-12-05 16:36 UTC, kudav commented
Note that due to the changes OMEG is now in the toroidal direction (no longer parallel to the toroidal field) and the sign is made parallel to the magnetic field by multiplication with BPHI. This introduced a small bug in the fidasim interface inconsistent with this new behavior, which I've adressed in #319.